## Exercise 1: Convert a list and tuple into arrays

In [2]:
import numpy as np
import sys

In [8]:
lst = [1,2,3,4,5,6,7,8]
tup = ([8,4,6],[1,2,3])
arr1=np.array(lst)
arr2=np.array(tup)
print(arr1)
print(arr2)



[1 2 3 4 5 6 7 8]
[[8 4 6]
 [1 2 3]]


List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]


## Also try np.asarray for the problem above! 

## Exercise 2:  Convert the values of Centigrade degrees into Fahrenheit degrees

In [21]:
fah=np.array([ 0.,12.,45.21,34.,99.91])
cel=np.array([])
for i in fah:
    c = (i - 32.0) * 5/9 
    cel=np.append(cel,c)
cel

array([-17.77777778, -11.11111111,   7.33888889,   1.11111111,
        37.72777778])

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


## Exercise 3: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. 

In [31]:
x = np.array([1,2,3], dtype=np.float64)
print("Size of the array: ", x.size)
print("Length of one array element in bytes: ", x.itemsize)
print("Total bytes consumed by the elements of the array: ", x.nbytes)

Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


## Exercise 4: Get the unique elements of an array

In [42]:
original=np.array([10,10, 20, 20, 30, 30])
res=np.unique(original)
print("Original array:\n", original)
print("Unique elements of the above array:\n", res)
org=np.array([[1,1], [2, 3]])
res1=np.unique(org)
print("Original array:\n", org)
print("Unique elements of the above array:\n", res1)


Original array:
 [10 10 20 20 30 30]
Unique elements of the above array:
 [10 20 30]
Original array:
 [[1 1]
 [2 3]]
Unique elements of the above array:
 [1 2 3]


Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]


## Exercise 5: Change the dimension of an array


In [46]:
res=np.array([1 ,2, 3, 4, 5, 6, 7, 8, 9])
res1=np.reshape(res,(3,3))
print("Original array:",res)
print("Result :",res1)

Original array: [1 2 3 4 5 6 7 8 9]
Result : [[1 2 3]
 [4 5 6]
 [7 8 9]]


Original array: [1 2 3 4 5 6 7 8 9]
Change array shape to (3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Exercise 6: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive

In [50]:
print(np.linspace(2.5,6.5,29))

[2.5        2.64285714 2.78571429 2.92857143 3.07142857 3.21428571
 3.35714286 3.5        3.64285714 3.78571429 3.92857143 4.07142857
 4.21428571 4.35714286 4.5        4.64285714 4.78571429 4.92857143
 5.07142857 5.21428571 5.35714286 5.5        5.64285714 5.78571429
 5.92857143 6.07142857 6.21428571 6.35714286 6.5       ]


## Exercise 7: Convert 1-D arrays as columns into a 2-D array

In [53]:
arr1=np.array([10 ,20 ,30])
arr2=np.array([40 ,50, 60])
print("converted array:")
print(np.stack((arr1,arr2),axis = 1))

converted array:
[[10 40]
 [20 50]
 [30 60]]


Array1: [10 20 30]
Array2: [40 50 60]
Converted array
[[10 40]
 [20 50]
 [30 60]]


## Exercise 8: Create a 5x5 matrix with row values ranging from 0 to 4

In [66]:
org=np.zeros((5,5))
for i in range(len(org)):
    org[i]=[0,1,2,3,4]
print(org)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## Exercise 9: Sum of all the multiples of 3 or 5 below 100

In [73]:
arr=np.array([])
for i in range(1,100):
    if i%3==0 or i%5==0:
        arr=np.append(arr,i)
print("",int(np.sum(arr)))


2318

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


## Exercise 10: Combine a one and a two dimensional array together and display their elements
##### Hint : np.nditer()

In [80]:
x = np.arange(4)
y = np.arange(4)
for a, b in np.nditer([x,y]):
    print(a,":",b)
    

0 : 0
1 : 1
2 : 2
3 : 3


In [111]:
x=np.array([0,1,2,3])
y=np.array([[0,1,2,3],[4,5,6,7]])
res=np.array([])
for a,b in np.nditer([x,y]):
    print("%d:%d"%(a,b),)
    

   

0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


## Exercise 11: Write a NumPy program to replace all elements of NumPy array that are greater than specified array.

In [7]:
arr=np.array([[0.42436315 ,0.48558583, 0.32924763],
 [0.7439979  ,0.58220701 ,0.38213418],
 [0.5097581  ,0.34528799, 0.1563123 ]])

print("original array:",arr)

arr[arr>.5]=.5

print("replaced array:",arr)

original array: [[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
replaced array: [[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


Original array:
[[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


## Exercise 12: Add a new row to an empty numpy array

In [30]:
arr=np.array([])
a1=np.array([10,20,30])
a2=np.array([40,50,60])
arr=np.stack((a1,a2))
arr

array([[10, 20, 30],
       [40, 50, 60]])

Empty array:
[]
After adding two new arrays:
[[10 20 30]
 [40 50 60]]


## Exercise 13: Write a NumPy program to join a sequence of arrays along a new axis. 

In [42]:
a1=np.array([1 ,2, 3])
a2=np.array([2,3,4])
print("Sequence of arrays along a new axis:",np.stack((a1,a2),axis=0))
a3=np.array([[1],[2],[3]])
a4=np.array([[2],[3],[4]])
print("Sequence of arrays along a new axis:",np.vstack((a3,a4)))


Sequence of arrays along a new axis: [[1 2 3]
 [2 3 4]]
Sequence of arrays along a new axis: [[1]
 [2]
 [3]
 [2]
 [3]
 [4]]


Original arrays:
[1 2 3]
[2 3 4]
Sequence of arrays along a new axis:
[[1 2 3]
 [2 3 4]]

Original arrays:
[[1]
 [2]
 [3]]

[[2]
 [3]
 [4]]
Sequence of arrays along a new axis:
[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]
